require: rubocop-rails
inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 2.6.6
  NewCops: enable

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/upload_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/upload_controller.rb'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Style/MixinUsage:
  Exclude:
    - 'features/step_definitions/*.rb'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/MissingSuper:
   Enabled: false
